name: artifact workflow

on: push

env:
  FILE_NAME: hello-server

jobs:
  build:
    name: build job
    runs: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
        run: go build ${{ env.FILE_NAME }}.go

      - name: Build for ${{ env.FILE_NAME }} for windows
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      - name: upload artifact for linux
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: .$/{{ env.FILE_NAME }}

      - name: upload artifact for windows
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  test_linux:
    name: test_linux
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: downlaod artifact
        uses: actions/download-artifact@v4
        with:
          name: linux

      - name: test ${{ env.FILE_NAME }}
        run: source ./test.sh

  test_windows:
    name: test_windows
    run-on: windows-latest
    nedds: [build]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows

      - name: test ${{ env.FILE_NAME }}
        run: windows/${{ env.FILE_NAME}}.exe
